"""Initial schema: RootCause and DiagnosticSession

Revision ID: fada02c1d3ab
Revises: 
Create Date: 2026-02-25 07:40:57.665954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fada02c1d3ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('obd_codes', sa.Text(), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('top_cause', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('repair_outcome', sa.String(length=50), nullable=True),
    sa.Column('torch_predictions', sa.JSON(), nullable=True),
    sa.Column('predicted_causes', sa.JSON(), nullable=True),
    sa.Column('confirmed_cause', sa.String(length=255), nullable=True),
    sa.Column('repair_parts', sa.Text(), nullable=True),
    sa.Column('training_ready', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_sessions_id'), 'diagnostic_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_make'), 'diagnostic_sessions', ['make'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_model'), 'diagnostic_sessions', ['model'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_training_ready'), 'diagnostic_sessions', ['training_ready'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_vin'), 'diagnostic_sessions', ['vin'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_year'), 'diagnostic_sessions', ['year'], unique=False)
    op.create_table('root_causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('symptom_hash', sa.String(length=64), nullable=False),
    sa.Column('symptom_text', sa.Text(), nullable=False),
    sa.Column('cause', sa.String(length=255), nullable=False),
    sa.Column('confirmed_cause', sa.String(length=255), nullable=False),
    sa.Column('obd_codes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('initial_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cause_confirmation', 'root_causes', ['make', 'model', 'year', 'confirmed_cause'], unique=False)
    op.create_index('idx_vehicle_symptom', 'root_causes', ['make', 'model', 'year', 'symptom_hash'], unique=False)
    op.create_index(op.f('ix_root_causes_cause'), 'root_causes', ['cause'], unique=False)
    op.create_index(op.f('ix_root_causes_confirmed'), 'root_causes', ['confirmed'], unique=False)
    op.create_index(op.f('ix_root_causes_id'), 'root_causes', ['id'], unique=False)
    op.create_index(op.f('ix_root_causes_make'), 'root_causes', ['make'], unique=False)
    op.create_index(op.f('ix_root_causes_model'), 'root_causes', ['model'], unique=False)
    op.create_index(op.f('ix_root_causes_symptom_hash'), 'root_causes', ['symptom_hash'], unique=False)
    op.create_index(op.f('ix_root_causes_year'), 'root_causes', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_root_causes_year'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_symptom_hash'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_model'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_make'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_id'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_confirmed'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_cause'), table_name='root_causes')
    op.drop_index('idx_vehicle_symptom', table_name='root_causes')
    op.drop_index('idx_cause_confirmation', table_name='root_causes')
    op.drop_table('root_causes')
    op.drop_index(op.f('ix_diagnostic_sessions_year'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_vin'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_training_ready'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_model'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_make'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_id'), table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    # ### end Alembic commands ###
